export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';

export const USER_LOADED_SUCCESS ='USER_LOADED_SUCCESFULLY';
export const USER_LOADED_ERROR ='USER_LOADED_ERROR';

export const LOGIN_SUCCESS ='LOGIN_SUCCESSFULLY';
export const LOGIN_ERROR ='LOGIN_ERROR';

export const GET_PROFILE ='GET_PROFILE';
export const PROFILE_ERROR ='PROFILE_ERROR';
export const UPDATE_PROFILE ='UPDATE_PROFILE';
export const GET_PROFILES ='GET_PROFILES';
export const CLEAR_PROFILE ='CLEAR_PROFILE';

export const ACCOUNT_DELETED ='ACCOUNT_DELETED';

export const LOGOUT ='LOGOUT';