export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';
export const USER_LOADED_SUCCESFULLY ='USER_LOADED_SUCCESFULLY';
export const USER_LOADED_ERROR ='USER_LOADED_ERROR';