export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESFULLY";
export const USER_LOADED_ERROR = "USER_LOADED_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESSFULLY";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const FILTER_PROFILES= "FILTER_PROFILES";

export const ADD_POST = "ADD_POST";
export const GET_POSTS = "GET_POSTS";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const DELETE_POST = "DELETE_POST";
export const GET_POST = "GET_POST";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const LOGOUT = "LOGOUT";
